# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestCase2AddaBooktoCart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testCase2AddaBooktoCart(self):
    self.driver.get("https://www.waterstones.com/")
    assert self.driver.title == "Buy books, stationery and gifts, online and in store | Waterstones"
    self.driver.find_element(By.NAME, "term").send_keys("Hello Beautiful")
    self.driver.find_element(By.CSS_SELECTOR, ".input-search-button").click()
    element = self.driver.find_element(By.LINK_TEXT, "Hello Beautiful")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Hello Beautiful").click()
    elements = self.driver.find_elements(By.ID, "scope_book_title")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".button-buy").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button-gold").click()
    elements = self.driver.find_elements(By.LINK_TEXT, "Hello Beautiful")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.XPATH, "//span[contains(@class, \'lblBasketTotalToPay\') and contains(text(), \'£13.99\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".btnCheckOutTablet > .btnBasketNext").click()
  
