# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestCase1BrowseBookCategories():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testCase1BrowseBookCategories(self):
    self.driver.get("https://www.waterstones.com/")
    assert self.driver.title == "Buy books, stationery and gifts, online and in store | Waterstones"
    assert self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) > .nav-item-books").text == "BOOKS"
    self.driver.find_element(By.LINK_TEXT, "Bestsellers").click()
    assert self.driver.title == "Best selling books | Waterstones"
    element = self.driver.find_element(By.XPATH, "//a[contains(@class, \'title\') and contains(@class, \'link-invert\') and contains(@class, \'dotdotdot\') and contains(@class, \'ddd-truncated\')]")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.LINK_TEXT, "Tomorrow, and…")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#p_12172931 img").click()
    elements = self.driver.find_elements(By.ID, "scope_book_title")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Waterstones").click()
  
